name: Check
on: [ pull_request, push ]
jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        # - windows-latest
        gradle_task:
        - ":embulk-decoder-bzip2:check"
        - ":embulk-decoder-gzip:check"
        - ":embulk-encoder-bzip2:check"
        - ":embulk-encoder-gzip:check"
        - ":embulk-filter-remove_columns:check"
        - ":embulk-filter-rename:check"
        - ":embulk-formatter-csv:check"
        - ":embulk-guess-bzip2:check"
        - ":embulk-guess-csv:check"
        - ":embulk-guess-csv_all_strings:check"
        - ":embulk-guess-gzip:check"
        - ":embulk-guess-json:check"
        - ":embulk-input-config:check"
        - ":embulk-input-file:check"
        - ":embulk-output-file:check"
        - ":embulk-output-null:check"
        - ":embulk-output-stdout:check"
        - ":embulk-parser-csv:check"
        - ":embulk-parser-json:check"
    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: "zulu"
    - name: Build and test
      run: ./gradlew ${{ matrix.gradle_task }}
